permalink: pretty
highlighter: rouge
url: https://tanakaoriginal.github.io/playbook/

collections:
  - plays
  - plays_ja_jp

markdown: kramdown

sass:
  sass_dir: assets/_sass

exclude:
  - .github/
  - .bundle/
  - .sass-cache/
  - node_modules/
  - .gitignore
  - .ruby-gemset
  - .ruby-version
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - package.json
  - README.md