name: Unit Test

on:
  push:
    branches:
      - '!gh-pages'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: npm install for development
        run: NODE_ENV=development npm install
      - name: Unit test
        run: npm run test:unit
